baseURL = 'https://www.schaerweb.com/'
googleAnalytics = 'UA-15165899-1'
languageCode = 'en-us'
title = 'Martin Schaer Web'
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true
sectionPagesMenu = "all"
[build]
  noJSConfigInAssets = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = 'Creative Technologist'
  images = ['notes/f1-ar/005.png']
  title = 'Martin Schaer Web'
[menu]
[[menu.main]]
  identifier = 'notes'
  name = 'Notes'
  title = 'Notes'
  url = '/notes/'
  weight = 1
[[menu.main]]
  identifier = 'f1'
  name = 'F1 VR Room'
  title = 'F1 VR Room'
  url = '/f1'
  weight = 2
[[menu.main]]
  identifier = 'linkedin'
  name = 'LinkedIn'
  title = 'LinkedIn'
  url = 'https://www.linkedin.com/in/martinschaer/'
  weight = 5
  [menu.main.params]
    target = "_blank"
