baseURL = 'https://www.schaerweb.com/'
canonifyURLs = true
enableGitInfo = true
enableRobotsTXT = true
googleAnalytics = 'UA-15165899-1'
languageCode = 'en-us'
sectionPagesMenu = "all"
title = 'Martin Schaer Web'
[build]
  noJSConfigInAssets = true
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
[params]
  description = 'Creative Technologist'
  images = ['articles/f1-3d/008.png']
  title = 'Martin Schaer Web'
[taxonomies]
  tag = 'tags'
[menu]
[[menu.main]]
  identifier = 'articles'
  name = 'Articles'
  title = 'Articles'
  url = '/articles/'
  weight = 1
[[menu.main]]
  identifier = 'about'
  name = 'About'
  title = 'About'
  url = '/about/'
  weight = 5
