/// <reference types="bun" />
// Generates db/profanity.surql from src/game/profanity.ts so the browser's
// pre-check and the database's authoritative check can never drift apart.
//
//   bun run db/gen-profanity.ts
import { PROFANITY_ALLOW, PROFANITY_EXACT, PROFANITY_SUB } from "../src/game/profanity";

const list = (words: Array<string>) =>
  words.map((word) => `  ${JSON.stringify(word)}`).join(",\n");

const out = `-- GENERATED by db/gen-profanity.ts from src/game/profanity.ts
-- Do not edit; edit the TypeScript list and regenerate.

DEFINE PARAM OVERWRITE $PROFANITY_SUB VALUE [
${list(PROFANITY_SUB)}
];

DEFINE PARAM OVERWRITE $PROFANITY_EXACT VALUE [
${list(PROFANITY_EXACT)}
];

DEFINE PARAM OVERWRITE $PROFANITY_ALLOW VALUE [
${list(PROFANITY_ALLOW)}
];
`;

await Bun.write(new URL("profanity.surql", import.meta.url), out);
console.log(
  `db/profanity.surql: ${PROFANITY_SUB.length} substring + ${PROFANITY_EXACT.length} exact + ${PROFANITY_ALLOW.length} allowed`,
);
